# -*- coding: utf-8 -*-
"""Aproveite a Oferta

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NMIR0g-64zXPWhkO_NXlSrWkT2gBz56D
"""

t = int(input())
while t > 0:
    t -= 1
    n, k = input().split()
    n = int(n)
    k = int(k)
    total = int(int(n % k) + int(n / k))
    print(total)